export default {
  IncreaseProduct: 'IncreaseProduct',
  IncreaseAddProduct: 'IncreaseAddProduct',
  ReduceProduct: 'ReduceProduct',
  ReduceListProduct: 'ReduceListProduct',
  GetShoppingCartItem: 'GetShoppingCartItem',
  ClearShoppingCartItem: 'ClearShoppingCartItem',
  addCartCount: 'addCartCount',
  minusCartCount: 'minusCartCount',
  keyNumCartCount: 'keyNumCartCount',
  GetMacValue: 'GetMacValue',
  GetBuyerDetail: 'GetBuyerDetail',
  GetshowAmtData: 'GetshowAmtData',
  PostGetTotalAmt: 'PostGetTotalAmt',
  GetLoginInfo: 'GetLoginInfo',
  PostLogin: 'PostLogin',
  PostAnoyLogin: 'PostAnoyLogin',
  PostRegister: 'PostRegister',
  LoginOut: 'LoginOut',
  SetLoginModal: 'SetLoginModal',
  GetLoginModal: 'GetLoginModal'
}
