export default {
  // Loading畫面顯示
  SetLoading: 'SetLoading',
  IncreaseProduct: 'IncreaseProduct',
  IncreaseAddProduct: 'IncreaseAddProduct',
  ReduceProduct: 'ReduceProduct',
  GetShoppingCartItem: 'GetShoppingCartItem',
  ClearShoppingCartItem: 'ClearShoppingCartItem',
  addCartCount: 'addCartCount',
  minusCartCount: 'minusCartCount',
  keyNumCartCount: 'keyNumCartCount',
  GetMacValue: 'GetMacValue',
  // 取得購買人資料
  GetBuyerDetail: 'GetBuyerDetail',
  // 存入購買人資料
  SetBuyerDetail: 'SetBuyerDetail',
  // 取得折扣碼
  GetCouponCode: 'GetCouponCode',
  GetshowAmtData: 'GetshowAmtData',
  PostGetTotalAmt: 'PostGetTotalAmt',
  GetLoginInfo: 'GetLoginInfo',
  PostLogin: 'PostLogin',
  PostAnoyLogin: 'PostAnoyLogin',
  PostRegister: 'PostRegister',
  LoginOut: 'LoginOut',
  // 開啟登入視窗
  SetLoginModal: 'SetLoginModal',
  // 關閉登入視窗
  GetLoginModal: 'GetLoginModal',
  // 設定步驟條
  SetCartStepBar: 'SetCartStepBar',
  // 存入優惠碼
  SetCouponCode: 'SetCouponCode',
  'PassNoticeFc': 'PassNoticeFc',
  // 購物車彈跳視窗
  'openCART': 'openCART',
  'GetOpenCart': 'GetOpenCart'
}
